[2023-12-18T01:38:12.281+0000] {taskinstance.py:1149} INFO - Dependencies not met for <TaskInstance: bitkub_dag.complete_Bitkub_etl scheduled__2021-01-01T00:00:00+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2023-12-18T01:38:12.281659+00:00 and task will be retried at 2023-12-18T01:38:56.239106+00:00.
[2023-12-18T01:38:12.289+0000] {local_task_job_runner.py:154} INFO - Task is not able to be run
[2023-12-18T01:40:08.091+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bitkub_dag.complete_Bitkub_etl scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-12-18T01:40:08.101+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bitkub_dag.complete_Bitkub_etl scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-12-18T01:40:08.101+0000] {taskinstance.py:1361} INFO - Starting attempt 4 of 4
[2023-12-18T01:40:08.224+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): complete_Bitkub_etl> on 2021-01-01 00:00:00+00:00
[2023-12-18T01:40:08.229+0000] {standard_task_runner.py:57} INFO - Started process 1209 to run task
[2023-12-18T01:40:08.233+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'bitkub_dag', 'complete_Bitkub_etl', 'scheduled__2021-01-01T00:00:00+00:00', '--job-id', '287', '--raw', '--subdir', 'DAGS_FOLDER/bitkub_dag.py', '--cfg-path', '/tmp/tmp1dklopgz']
[2023-12-18T01:40:08.234+0000] {standard_task_runner.py:85} INFO - Job 287: Subtask complete_Bitkub_etl
[2023-12-18T01:40:08.268+0000] {task_command.py:416} INFO - Running <TaskInstance: bitkub_dag.complete_Bitkub_etl scheduled__2021-01-01T00:00:00+00:00 [running]> on host ip-172-31-6-101.ca-central-1.compute.internal
[2023-12-18T01:40:08.313+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='bitkub_dag' AIRFLOW_CTX_TASK_ID='complete_Bitkub_etl' AIRFLOW_CTX_EXECUTION_DATE='2021-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-01-01T00:00:00+00:00'
[2023-12-18T01:40:08.314+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ubuntu/airflow/bitkub_dag/bitkub_etl.py", line 55, in Bitkub_etl
    list_btc=[data_json]
UnboundLocalError: local variable 'data_json' referenced before assignment
[2023-12-18T01:40:08.318+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=bitkub_dag, task_id=complete_Bitkub_etl, execution_date=20210101T000000, start_date=20231218T014008, end_date=20231218T014008
[2023-12-18T01:40:08.330+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 287 for task complete_Bitkub_etl (local variable 'data_json' referenced before assignment; 1209)
[2023-12-18T01:40:08.364+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-18T01:40:08.378+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
