[2023-12-18T03:26:10.173+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_dag_decorator.send_email manual__2023-12-18T03:25:49+00:00 [queued]>
[2023-12-18T03:26:10.184+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_dag_decorator.send_email manual__2023-12-18T03:25:49+00:00 [queued]>
[2023-12-18T03:26:10.185+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-18T03:26:10.202+0000] {taskinstance.py:1382} INFO - Executing <Task(EmailOperator): send_email> on 2023-12-18 03:25:49+00:00
[2023-12-18T03:26:10.208+0000] {standard_task_runner.py:57} INFO - Started process 1196 to run task
[2023-12-18T03:26:10.217+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'example_dag_decorator', 'send_email', 'manual__2023-12-18T03:25:49+00:00', '--job-id', '361', '--raw', '--subdir', '/usr/local/lib/python3.10/dist-packages/airflow/example_dags/example_dag_decorator.py', '--cfg-path', '/tmp/tmppldvyuei']
[2023-12-18T03:26:10.219+0000] {standard_task_runner.py:85} INFO - Job 361: Subtask send_email
[2023-12-18T03:26:10.258+0000] {task_command.py:416} INFO - Running <TaskInstance: example_dag_decorator.send_email manual__2023-12-18T03:25:49+00:00 [running]> on host ip-172-31-6-101.ca-central-1.compute.internal
[2023-12-18T03:26:10.321+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='example_dag_decorator' AIRFLOW_CTX_TASK_ID='send_email' AIRFLOW_CTX_EXECUTION_DATE='2023-12-18T03:25:49+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-18T03:25:49+00:00'
[2023-12-18T03:26:10.332+0000] {logging_mixin.py:154} WARNING - /usr/local/lib/python3.10/dist-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2023-12-18T03:26:10.333+0000] {configuration.py:1050} WARNING - section/key [smtp/smtp_user] not found in config
[2023-12-18T03:26:10.333+0000] {email.py:270} INFO - Email alerting: attempt 1
[2023-12-18T03:26:10.334+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/email.py", line 77, in execute
    send_email(
  File "/usr/local/lib/python3.10/dist-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/usr/local/lib/python3.10/dist-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/usr/local/lib/python3.10/dist-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/usr/local/lib/python3.10/dist-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.10/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2023-12-18T03:26:10.430+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=example_dag_decorator, task_id=send_email, execution_date=20231218T032549, start_date=20231218T032610, end_date=20231218T032610
[2023-12-18T03:26:10.447+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 361 for task send_email ([Errno 111] Connection refused; 1196)
[2023-12-18T03:26:10.471+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-18T03:26:10.486+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
