[2023-12-18T01:35:39.400+0000] {taskinstance.py:1149} INFO - Dependencies not met for <TaskInstance: bitkub_dag.complete_Bitkub_etl scheduled__2020-12-20T00:00:00+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2023-12-18T01:35:39.400795+00:00 and task will be retried at 2023-12-18T01:36:03.174621+00:00.
[2023-12-18T01:35:39.408+0000] {local_task_job_runner.py:154} INFO - Task is not able to be run
[2023-12-18T01:37:12.764+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bitkub_dag.complete_Bitkub_etl scheduled__2020-12-20T00:00:00+00:00 [queued]>
[2023-12-18T01:37:12.770+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bitkub_dag.complete_Bitkub_etl scheduled__2020-12-20T00:00:00+00:00 [queued]>
[2023-12-18T01:37:12.770+0000] {taskinstance.py:1361} INFO - Starting attempt 4 of 4
[2023-12-18T01:37:12.785+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): complete_Bitkub_etl> on 2020-12-20 00:00:00+00:00
[2023-12-18T01:37:12.788+0000] {standard_task_runner.py:57} INFO - Started process 1077 to run task
[2023-12-18T01:37:12.792+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'bitkub_dag', 'complete_Bitkub_etl', 'scheduled__2020-12-20T00:00:00+00:00', '--job-id', '257', '--raw', '--subdir', 'DAGS_FOLDER/bitkub_dag.py', '--cfg-path', '/tmp/tmp5jchircc']
[2023-12-18T01:37:12.793+0000] {standard_task_runner.py:85} INFO - Job 257: Subtask complete_Bitkub_etl
[2023-12-18T01:37:12.831+0000] {task_command.py:416} INFO - Running <TaskInstance: bitkub_dag.complete_Bitkub_etl scheduled__2020-12-20T00:00:00+00:00 [running]> on host ip-172-31-6-101.ca-central-1.compute.internal
[2023-12-18T01:37:12.879+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='bitkub_dag' AIRFLOW_CTX_TASK_ID='complete_Bitkub_etl' AIRFLOW_CTX_EXECUTION_DATE='2020-12-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2020-12-20T00:00:00+00:00'
[2023-12-18T01:37:12.880+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ubuntu/airflow/bitkub_dag/bitkub_etl.py", line 55, in Bitkub_etl
    list_btc=[data_json]
UnboundLocalError: local variable 'data_json' referenced before assignment
[2023-12-18T01:37:12.883+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=bitkub_dag, task_id=complete_Bitkub_etl, execution_date=20201220T000000, start_date=20231218T013712, end_date=20231218T013712
[2023-12-18T01:37:12.895+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 257 for task complete_Bitkub_etl (local variable 'data_json' referenced before assignment; 1077)
[2023-12-18T01:37:12.930+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-18T01:37:12.945+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
